config/routes.rb
Rails.application.routes.draw do
  root to: 'memos#index'
  resources :memos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def index
    @memos = Memo.all
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    redirect_to memos_path
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    @memo = Memo.find(params[:id])
    @memo.update(memo_params)
    redirect_to memos_path
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to memos_path
  end

  private
    def memo_params
      params.require(:memo).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/edit.html.erb
<h1>メモ編集</h1>
<%= form_for(@memo) do |f| %>
  <div><%= f.label :title %></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', memos_path %>

app/views/memos/index.html.erb
<header class="header">
<h1 class="memo-header">メモ一覧</h1>
</header>
 <div class="memo-tuika"><%= link_to 'メモを追加', new_memo_path %></div>
  <div class="memo-title">
    <% @memos.each do |memo| %>
        <p><%= memo.title %></p>
        <p><%= link_to '編集', edit_memo_path(memo) %></p>
        <p><%= link_to '削除', memo_path(memo), method: :delete %></p>
        
    <% end %>

app/views/memos/new.html.erb
<div class="header2"></div>
<h1 class="sinki-memo">新規メモ</h1>
<%= form_for(@memo) do |f| %>
  <div class="memo-nyuuryoku">
  <div><%= f.text_field :title %>
  <div><%= f.submit "メモ投稿" %>
  <div><%= link_to '戻る', memos_path %>
  </div>
  </div>
  </div>
  </div>
<% end %>